from supabase import create_client, Client
import os

SUPABASE_URL = "https://ywhgmyyqxvxebacnmaix.supabase.co"
SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3aGdteXlxeHZ4ZWJhY25tYWl4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MzgwNjU2MywiZXhwIjoyMDY5MzgyNTYzfQ.-dojUf6gN9R4DAyeBm_c6uAX5kDcYhLMqX70JZDInvE"

supabase: Client = create_client(SUPABASE_URL, SERVICE_ROLE_KEY)